modLoader="javafml"
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]]
modId="khalivampirism"
version="1.0"
displayName="Khali Vampirism" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this mod goes to my brother for spriting and brainstorming with me and turty wurty on youtube for tutorials" #optional
authors="Khali Rai, Grog" #optional
description='''
this mod just makes vampirism the way I envision it
'''